# Generated by Django 4.2.2 on 2023-07-07 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_m7app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='observacion',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
