# Generated by Django 4.2.2 on 2023-07-07 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('individual_m7app', '0001_initial'),
    ]

    operations = [

        migrations.AddField(
            model_name='task',
            name='prioridad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='individual_m7app.prioridad'),
        ),
    ]
