# Generated by Django 4.2.2 on 2023-07-07 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('individual_m7app', '0003_task_observacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[(1, 'Prioridad Alta'), (2, 'Prioridad Normal'), (3, 'Prioridad Baja')], max_length=20)),
                ('orden', models.IntegerField(unique=True)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
    ]
